global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "clash"
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:2112"]
